package net.smilegate.fim.enums;

public enum Currency {
    AUD("호주")
    ,AFN("아프카니스탄")
    ,ALL("알바니아")
    ,AMD("아르메니아")
    ,AOA("앙골라")
    ,ATS("오스트리아")
    ,ARS("아르헨티나")
    ,AWG("아루바")
    ,AZN("아제르바이잔")
    ,BSD("바하마")
    ,BHD("바레인")
    ,BDT("방글라데시")
    ,BBD("바베이도스")
    ,BYR("벨라루스")
    ,BZD("벨리즈")
    ,BMD("버뮤다")
    ,BTN("부탄")
    ,BOB("볼리비아노")
    ,BWP("보츠와나")
    ,BRL("브라질")
    ,BND("브루나이")
    ,BGN("불가리아")
    ,BIF("부룬디")
    ,BEF("벨기에")
    ,BYN("벨로루시")
    ,CAD("캐나다")
    ,CNY("중국")
    ,CVE("카보베르데")
    ,CLP("칠레")
    ,CUP("쿠바")
    ,CZK("체코")
    ,COP("콜롬비아")
    ,CRC("코스타리카")
    ,DZD("알제리")
    ,DKK("덴마크")
    ,DEM("독일")
    ,DJF("지부티")
    ,DOP("도미니카 공화국")
    ,EUR("유로")
    ,EGP("이집트")
    ,EEK("에스토니아")
    ,ETB("에티오피아")
    ,ECS("에콰도르")
    ,ESP("스페인")
    ,FKP("포클랜드 제도")
    ,FRF("프랑스")
    ,FJD("피지")
    ,FIM("핀란드")
    ,KHR("캄보디아")
    ,KYD("케이맨 제도")
    ,GBP("영국")
    ,KMF("코모로")
    ,HRK("크로아티아")
    ,XCD("동카리브")
    ,SVC("엘살바도르")
    ,GMD("감비아")
    ,GTQ("과테말라")
    ,GNF("기니")
    ,GYD("가이아나")
    ,GHS("가나")
    ,GAF("-")
    ,GEL("조지아")
    ,GIP("지브롤터")
    ,HKD("홍콩")
    ,HTG("아이티")
    ,HNL("온두라스")
    ,HUF("헝가리")
    ,IDR("인도네시아")
    ,INR("인도")
    ,ISK("아이슬란드")
    ,IRR("이란")
    ,IQD("이라크")
    ,ILS("이스라엘")
    ,ITL("이탈리아")
    ,JPY("일본")
    ,JOD("요르단")
    ,JMD("자메이카")
    ,KZT("카자흐스탄")
    ,KES("케냐")
    ,KRW("대한민국")
    ,KWD("쿠웨이트")
    ,KPW("조선민주주의인민공화국")
    ,KGS("키르기스스탄")
    ,LAK("라오인민민주공화국 (THE)")
    ,LRD("라이베리아")
    ,LBP("레바논")
    ,LSL("레소토")
    ,LYD("리비아")
    ,MGA("마디가스카르")
    ,MZN("모잠비크")
    ,MOP("마카오")
    ,MKD("마케도니아")
    ,MWK("말라위")
    ,MYR("말레이시아")
    ,MVR("몰디브")
    ,MRO("모리타니")
    ,MUR("모리셔스")
    ,MXN("멕시코")
    ,MDL("몰도바")
    ,MNT("몽골")
    ,MAD("모로코")
    ,MMK("미얀마")
    ,NAD("나미비아")
    ,NPR("네팔")
    ,NLG("네덜란드")
    ,ANG("네덜란드령 안틸레스")
    ,NZD("뉴질랜드")
    ,NIO("니카라과")
    ,NGN("나이지리아")
    ,NOK("노르웨이")
    ,OMR("오만")
    ,RSD("세르비아")
    ,PKR("파키스탄")
    ,PAB("파나마")
    ,PGK("파푸아 뉴기니")
    ,PYG("파라과이")
    ,PEN("페루")
    ,PHP("필리핀")
    ,PLN("폴란드")
    ,QAR("카타르")
    ,RON("루마니아")
    ,RUB("러시아")
    ,RWF("르완다")
    ,CHF("스위스")
    ,WST("사모아")
    ,STD("상투메")
    ,SAR("사우디아라비아")
    ,SCR("세이셸")
    ,SLL("시에라리온")
    ,SDR("국제 통화 기금(IMF)")
    ,SGD("싱가폴")
    ,SRD("수리남")
    ,SKK("슬로바키아")
    ,SBD("솔로몬 제도")
    ,SOS("소말리아")
    ,ZAR("남아프리카 공화국")
    ,LKR("스리랑카")
    ,SHP("세인트헬레나")
    ,SDG("수단")
    ,SZL("스와질란드")
    ,SEK("스웨덴")
    ,SYP("시리아")
    ,THB("태국")
    ,TRY("터키어")
    ,TWD("대만")
    ,TZS("탄자니아")
    ,TOP("통가")
    ,TMT("투르크메니스탄")
    ,TTD("트리니다드 토바고")
    ,TND("튀니지")
    ,USD("미국")
    ,AED("아랍에미리트")
    ,UGX("우간다")
    ,UAH("우크라이나")
    ,UYU("우루과이")
    ,UZS("우즈베크")
    ,VUV("바누아투")
    ,VND("베트남")
    ,VEF("볼리바르")
    ,VES("베네수엘라")
    ,XPF("CFP")
    ,XOF("CFA 프랑 (BCEAO)")
    ,XAF("CFA 프랑 (BEAC)")
    ,YER("예멘")
    ,ZMW("잠비아")
    ;
    
    private String currNm;
    
    Currency(String currNm) {
        this.currNm = currNm;
    }
    
    public String getCurrNm() {
        return currNm;
    }
    
}
