var deptVO = {};

function addExpense() {
    html = '';
    html += '<tr>                                                                                                 ';
    html += '    <td class="table__td">                                                                                     ';
    html += '        <div class="btn_group">                                                                                 ';
    html += '            <span class="btn-checkbox">                                                                             ';
    html += '                <input type="checkbox" id="checkbox_memberChk1" class="checkbox_member-leave">                                                     ';
    html += '                <label for="checkbox_memberChk1" class="btn-checkbox__label"><span class="blind">선택</span></label>                                         ';
    html += '            </span>                                                                                         ';
    html += '        </div>                                                                                             ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td table__td--data">                                                                             ';
    html += '        <span class="table__txt"></span>                                                                             ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td table__td--btn">                                                                             ';
    html += '        <span class="table__txt">홍길동A<br>정보개발시스템실</span>                                                                     ';
    html += '        <button type="button" class="btn btn-change-user" onclick="openUserPopup();">                                                         ';
    html += '            <span class="sp icon-change-user"><span class="blind">사용자 선택</span></span>                                                     ';
    html += '        </button>                                                                                         ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td">                                                                                     ';
    html += '        <div class="input-field input-field-table">                                                                         ';
    html += '            <input type="text" class="input-field__input" placeholder="선택해주세요.">  ';
    html += '        </div>                                                                                             ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td table__td--data">                                                                             ';
    html += '        <span class="table__txt"></span>                                                                             ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td table__td--data">                                                                             ';
    html += '        <div class="input-field input-field-table">                                                                         ';
    html += '            <input type="text" class="input-field__input" placeholder="선택해주세요."> ';
    html += '        </div>                                                                                             ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td table__td--data">                                                                             ';
    html += '        <span class="table__txt"></span>                                                                             ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td">                                                                                     ';
    html += '        <div class="input-field input-field-table">                                                                         ';
    html += '            <input type="text" class="input-field__input" placeholder="입력해주세요.">                                                          ';
    html += '        </div>                                                                                             ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td">                                                                                     ';
    html += '        <div class="input-field datepicker__v-calendar">                                                                     ';
    html += '        </div>                                                                                             ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td">                                                                                     ';
    html += '        <div class="input-field input-field-table">                                                                         ';
    html += '            <input type="text" class="input-field__input" placeholder="입력해주세요.">                                                          ';
    html += '        </div>                                                                                             ';
    html += '        <span class="table__txt table__txt-caption txt--blue"></span>                                                                 ';
    html += '    </td>                                                                                             ';
    html += '    <td class="table__td">                                                                                     ';
    html += '        <div class="input-field input-field-table">                                                                         ';
    html += '            <input type="text" class="input-field__input table__txt--align-right" placeholder="입력해주세요.">                                              ';
    html += '        </div>                                                                                             ';
    html += '    </td>                                                                                             ';
    html += '</tr>                                                                                                ';
}
